root: true
env:
  node: true
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    jsx: true
plugins:
  - react
rules:
  indent:
  - 2
  - 2
  quotes:
  - 2
  - "single"
  - "avoid-escape"
  linebreak-style:
  - 2
  - "unix"
  semi:
  - 2
  - "always"
  no-console: 0
  space-before-function-paren:
  - 2
  - anonymous: "always"
    named: "never"
  react/jsx-uses-react:
  - 2
  react/jsx-uses-vars:
  - 2
  react/react-in-jsx-scope:
  - 2
extends: "eslint:recommended"
