root: true
env:
  node: true
rules:
  indent:
  - 2
  - 4
  quotes:
  - 2
  - "single"
  - "avoid-escape"
  linebreak-style:
  - 2
  - "unix"
  semi:
  - 2
  - "always"
  no-console: 0
  space-before-function-paren:
  - 2
  - anonymous: "always"
    named: "never"
extends: "eslint:recommended"
